<?php

return [
    'base_url' => env('RAJAONGKIR_BASE_URL', 'https://rajaongkir.komerce.id/api/v1'),
    'cost_endpoint' => env('RAJAONGKIR_COST_ENDPOINT', '/calculate/district/domestic-cost'),
    'tracking_endpoint' => env('RAJAONGKIR_TRACKING_ENDPOINT', '/track/waybill'),
    'couriers' => [
        'anteraja' => 'AnterAja',
        'express21' => '21 Express',
        'expedito' => 'Expedito',
        'idexpress' => 'IDexpress Service Solution',
        'indotama' => 'Indotama Domestik Lestari',
        'indah' => 'Indah Logistic',
        'jet' => 'JET Express',
        'jne' => 'Jalur Nugraha Ekakurir (JNE)',
        'jnt' => 'J&T Express',
        'jtl' => 'JTL Express',
        'lion' => 'Lion Parcel',
        'ninja' => 'Ninja Xpress',
        'pahala' => 'Pahala Express',
        'pandu' => 'Pandu Logistics',
        'pcp' => 'PCP',
        'pos' => 'POS Indonesia',
        'rex' => 'Royal Express Indonesia',
        'rpx' => 'RPX',
        'sap' => 'SAP Express',
        'sentral' => 'Sentral Cargo',
        'sicepat' => 'SiCepat Express',
        'solusi' => 'Solusi Ekspres',
        'star' => 'Star Cargo',
        'tiki' => 'TIKI',
        'wahana' => 'Wahana Express',
    ],
];
